# To run: conda env create -f environment.yml
name: nerf
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - cudatoolkit=10.0
    - torch>=1.8
    - torchvision>=0.9.1
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - configargparse
    - tensorboard>=2.0
    - tqdm
    - opencv-python
    - scikit-learn
    # may not be needed
    - scikit-image
    - torchsummary 
